### ISSUE TITLE
KEMP Loadmaster MP doesn't discover my KEMP's

### ISSUE THREAD

**Issue by schoemandre** [QuaeNocentDocent/SCOMSNMP-MP#1]
I have configured my KEMP NLB for SNMP then tested it with a MIB Browser from my SCOM Network Discovery Management Server and it works.
I then configured the network discovery in SCOM with the correct community etc and that works as well however the Management Pack isn't discovering the KEMP's to populate the dashboards
My suspicion is that the KEMP firmware is too old...?
See attached screenshots of how I have everything congigured. 

![08-09-2016 09-30-37](https://cloud.githubusercontent.com/assets/18502425/18384972/9ef4f3f8-7685-11e6-9cc6-6dc322500d49.png)
![08-09-2016 09-32-31](https://cloud.githubusercontent.com/assets/18502425/18385039/0b5bb0ea-7686-11e6-8353-e0d78f98428a.png)
![08-09-2016 09-35-05](https://cloud.githubusercontent.com/assets/18502425/18385043/0d844652-7686-11e6-8b9a-abc17e29aa1f.png)
![08-09-2016 10-43-42](https://cloud.githubusercontent.com/assets/18502425/18385081/4295287a-7686-11e6-8844-fe4140d73df9.png)

**Comment by brandubh** [comment]
HI schoemandre, the issue is that your device seems to have a non standard SystemObjectID, afaik the Kemp one should be .1.3.6.1.4.1.12196.250.10, while your device reports .1.3.6.1.4.1.2021.250.10, that is ucdSnmpAgent=Linux. Never ever seen a Kemp device reporting as a Linux distro.

**Comment by brandubh** [comment]
Answering to your question it can indeed be a firmware issue, for example have a device here at version 1.2.1 and release 7.1.34.1.12802.RELEASE that is perfectly fine, I see yours are pretty outdated at versione 6.0, I would suggest an upgrade.
