### ISSUE TITLE
HA configuration

### ISSUE THREAD

**Issue by msacharewicz** [QuaeNocentDocent/SCOMSNMP-MP#5]
Hi,

With HA configuration, how will your MP work when monitoring two nodes?

- Will the VirtualServer and RealServer objects be doubled?
- Will the failure of one node generate alerts for VirtualServer and RealServer objects as well, even if the failover was successfull?

Thanks,
MS.

**Comment by brandubh** [comment]
hi Michal, if memory serves HA is supported, you must discover both nodes and everything should run smoothly. Clustering on the other hand is something I didn't have a chance to test, so it probably won't work.
